networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: wlp1s0
    ipam:
      config:
        - subnet: 10.64.0.0/16
          gateway: 10.64.0.1
          ip_range: 10.64.3.96/29
  internal:
    driver: bridge

services:
  broodwar-bot-1:
    build:
      context: .
      dockerfile: protossbot/Dockerfile
    container_name: broodwar-protoss-bot-1
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 10.64.3.100
      internal:

  broodwar-bot-2:
    build:
      context: .
      dockerfile: protossbot/Dockerfile
    container_name: broodwar-protoss-bot-2
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 10.64.3.101
      internal:

  broodwar-bot-3:
    build:
      context: .
      dockerfile: protossbot/Dockerfile
    container_name: broodwar-protoss-bot-3
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 10.64.3.102
      internal:

  novnc-bot-1:
    build:
      context: .
      dockerfile: novnc.Dockerfile
      args:
        VNC_SERVER: broodwar-bot-1:5900
    container_name: novnc-viewer-bot-1
    ports:
      - 6081:6080
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - broodwar-bot-1

  novnc-bot-2:
    build:
      context: .
      dockerfile: novnc.Dockerfile
      args:
        VNC_SERVER: broodwar-bot-2:5900
    container_name: novnc-viewer-bot-2
    ports:
      - 6082:6080
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - broodwar-bot-2

  novnc-bot-3:
    build:
      context: .
      dockerfile: novnc.Dockerfile
      args:
        VNC_SERVER: broodwar-bot-3:5900
    container_name: novnc-viewer-bot-3
    ports:
      - 6083:6080
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - broodwar-bot-3

  dashboard:
    image: nginx:alpine
    container_name: broodwar-dashboard
    ports:
      - 8080:80
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - internal
